/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#5516be',
        'secondary-fixed-dim': '#00e29e',
        'surface': '#101418',
        'on-tertiary-fixed-variant': '#6900b3',
        'tertiary': '#ddb7ff',
        'surface-container-high': '#262a2f',
        'secondary-container': '#00e5a0',
        'background': '#101418',
        'on-tertiary-container': '#400071',
        'secondary': '#6cffbf',
        'on-secondary-fixed': '#002114',
        'on-primary-fixed': '#23005c',
        'on-error': '#690005',
        'surface-dim': '#101418',
        'outline': '#958ea0',
        'inverse-surface': '#e0e3e8',
        'inverse-primary': '#6d3bd7',
        'on-secondary': '#003824',
        'surface-container-highest': '#31353a',
        'surface-container': '#1c2024',
        'tertiary-fixed': '#f0dbff',
        'inverse-on-surface': '#2d3135',
        'on-tertiary-fixed': '#2c0051',
        'surface-variant': '#31353a',
        'surface-tint': '#d0bcff',
        'on-secondary-fixed-variant': '#005236',
        'surface-bright': '#353a3e',
        'error': '#ffb4ab',
        'outline-variant': '#494454',
        'primary': '#d0bcff',
        'tertiary-container': '#b76dff',
        'surface-container-lowest': '#0a0f13',
        'primary-container': '#a078ff',
        'on-primary-container': '#340080',
        'surface-container-low': '#181c20',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#47ffb8',
        'on-primary': '#3c0091',
        'on-tertiary': '#490080',
        'on-surface': '#e0e3e8',
        'on-background': '#e0e3e8',
        'tertiary-fixed-dim': '#ddb7ff',
        'on-secondary-container': '#006141',
        'primary-fixed-dim': '#d0bcff',
        'error-container': '#93000a',
        'on-surface-variant': '#cbc3d7',
        'primary-fixed': '#e9ddff',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'gutter': '1.5rem',
        'space-xl': '2.5rem',
        'margin': '2rem',
        'gutter-sm': '1rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'margin-mobile': '1rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'metric-val': ['"JetBrains Mono"', 'monospace'],
        'display-hero': ['"Geist"', 'sans-serif'],
        'body-sm': ['"Inter"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'code-inline': ['"JetBrains Mono"', 'monospace'],
        'code-base': ['"JetBrains Mono"', 'monospace'],
        'body-lg': ['"Inter"', 'sans-serif'],
        'headline-lg': ['"Geist"', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
        'display-hero-mobile': ['"Geist"', 'sans-serif'],
        'headline-md': ['"Geist"', 'sans-serif'],
        'headline-lg-mobile': ['"Geist"', 'sans-serif'],
      },
      fontSize: {
        'metric-val': ['2rem', { lineHeight: '2.25rem', fontWeight: '600' }],
        'display-hero': ['3.75rem', { lineHeight: '4rem', fontWeight: '700' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'code-inline': ['0.8125rem', { lineHeight: '1rem', fontWeight: '500' }],
        'code-base': ['0.875rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
        'headline-lg': ['2.5rem', { lineHeight: '2.75rem', fontWeight: '600' }],
        'label-mono': ['0.75rem', { lineHeight: '1rem', fontWeight: '500' }],
        'display-hero-mobile': ['2.25rem', { lineHeight: '2.5rem', fontWeight: '700' }],
        'headline-md': ['1.5rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '2rem', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
